### ISSUE TITLE
build fails with bleloc/MetropolisSample.hpp not found

### ISSUE THREAD

**Issue by loopRW** [hulop/NavCog2#32] opened 2016-07-05 16:51 UTC
Current master (2c20acl) includes blelocpp 1.0.4 in podspecs. With this version NavCog fails to build.
If I manually include current blelocpp master, each time I load a map using pdr, NavCog crashes immediately with line:

Assertion failed: (nSamples>0), function randomSampleLocationsWithPerturbation, file ble-cpp/src/impl/StatusInitializerImpl.cpp, line 115.

**Comment by muratams** [comment] 2016-07-06 02:56
The build error will be fixed by updating Podfile in NavCogIOS.

Actually, the assertion error was caused by PNG-related settings in xcode project and has been fixed.

**Closed as completed** 2016-07-06 14:38 UTC
